server.port=8000
spring.application.name=web

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/EzyPos?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Makes the SQL in the console pretty and easy to read
spring.jpa.properties.hibernate.format_sql=true

# Only keep this if you are using an older Swagger version (SpringFox)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher